language: python

# Test on python3
python:
  - 3.5 # debian
  - 3.6 # ubuntu / amazonlinux
  - nightly

# Allow failures on cpython nightly build
matrix:
  fast_finish: true
  allow_failures:
    - python: nightly

install:
- pip install -r cyclone/tests/test_requirements.txt
- pip install coveralls

# cyclone has to be installed 
# so as trial (twisted test framework) could run
before_script: python setup.py install

script: coverage run `which trial` cyclone
after_success: coveralls

# deploy on pypi
# only on 3.6 (avoid multiple deployment)
deploy:
  provider: pypi
  user: fiorix
  password:
    secure: EgUIImke5aN2Q9ybtPfB1RDtvYLouJSjhvetdIWiUJZHxeViaufQQBv2eXkyUaIvwYAagfhnCNSR4Ql9mNr/nksSGvJ+tn9AH014OUSpPcrdmDMZdImWPo7hraNNnEs+pG7an6faBdLDYRtTv8Hx74dW54jCmo9AYBBelwklxwA=
  on:
    tags: true
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = 3.6
  distributions: "sdist bdist_wheel"
