language: python

# Test on python3
python:
  - 3.5 # debian
  - 3.6 # ubuntu / amazonlinux
  - 3.7 # fedora
  - nigthly
allow_failures: nigthly
dis: xenial

install:
- pip install -r cyclone/tests/test_requirements.txt
- pip install coveralls
script: coverage run `which trial` cyclone
after_success: coveralls
deploy:
  provider: pypi
  user: fiorix
  password:
    secure: EgUIImke5aN2Q9ybtPfB1RDtvYLouJSjhvetdIWiUJZHxeViaufQQBv2eXkyUaIvwYAagfhnCNSR4Ql9mNr/nksSGvJ+tn9AH014OUSpPcrdmDMZdImWPo7hraNNnEs+pG7an6faBdLDYRtTv8Hx74dW54jCmo9AYBBelwklxwA=
  on:
    tags: true
    branch: master
  distributions: "sdist bdist_wheel"
